#server.servlet.context-path=/churchsong
spring.application.name=ChurchSong

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/church-song
spring.datasource.name=church-song
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:868510433425-041gviefofsts3tjinm2qunil3bdkvvg.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=name

spring.security.oauth2.client.registration.yandex.client-id=c1b0c2261c0846b6af7efbf5150effab
spring.security.oauth2.client.registration.yandex.client-secret=494abaeb842845e1bed7c99cd3c04446
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.scope=login:info,login:email
spring.security.oauth2.client.registration.yandex.redirect-uri=http://localhost:8080/login/oauth2/code/yandex

spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info
spring.security.oauth2.client.provider.yandex.user-name-attribute=login

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.security.web.DefaultRedirectStrategy=DEBUG

telegram.bot.token=8357098240:AAFLGrnXPy0oYJNAmLItEm8pLPkWAYoN3K8
telegram.bot.username=ChurchSong_bot


logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.web.servlet=DEBUG
logging.level.org.springframework.security.web.filter=DEBUG

# ??????????? ??????
logging.level.org.springframework.session=DEBUG

spring.mvc.log-request-details=true
